"""add_system_settings

Revision ID: 02febd8e12f4
Revises: eeba8c003128
Create Date: 2026-06-12 00:05:22.921802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02febd8e12f4'
down_revision = 'eeba8c003128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_enabled', sa.Boolean(), nullable=True),
    sa.Column('registration_start_date', sa.DateTime(), nullable=True),
    sa.Column('registration_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
