"""Initial migration

Revision ID: 35d114451b97
Revises: 
Create Date: 2026-06-10 12:17:28.761359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d114451b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('lastname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('candidate_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('election_period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_period_id'], ['election_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('voter_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('election_period_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_period_id'], ['election_period.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voter_period_association',
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('election_period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_period_id'], ['election_period.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], )
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dignity', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('candidate_list_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_list_id'], ['candidate_list.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_period_id', sa.Integer(), nullable=False),
    sa.Column('candidate_list_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_list_id'], ['candidate_list.id'], ),
    sa.ForeignKeyConstraint(['election_period_id'], ['election_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('candidate')
    op.drop_table('audit_log')
    op.drop_table('voter_period_association')
    op.drop_table('voter_participation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('candidate_list')
    op.drop_table('voter')
    op.drop_table('election_period')
    # ### end Alembic commands ###
