"""add_face_descriptor_to_voter

Revision ID: c5d74b988086
Revises: 02febd8e12f4
Create Date: 2026-06-12 00:21:33.915223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d74b988086'
down_revision = '02febd8e12f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_descriptor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_column('face_descriptor')

    # ### end Alembic commands ###
