"""Add backup_generated to ElectionPeriod

Revision ID: da6ed40bec95
Revises: f97ce78e9324
Create Date: 2026-06-11 23:02:54.672886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6ed40bec95'
down_revision = 'f97ce78e9324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election_period', schema=None) as batch_op:
        batch_op.drop_column('backup_generated')

    # ### end Alembic commands ###
