"""Add Dignity model

Revision ID: f97ce78e9324
Revises: 5c36a9a53c8d
Create Date: 2026-06-10 14:27:04.992313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f97ce78e9324'
down_revision = '5c36a9a53c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dignity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('election_period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_period_id'], ['election_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dignity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dignity', ['dignity_id'], ['id'])
        batch_op.drop_column('dignity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dignity', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dignity_id')

    op.drop_table('dignity')
    # ### end Alembic commands ###
